#!/bin/sh

# Mount /proc and /sysfs

mkdir -p /proc
mkdir -p /sys
mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir /etc

# Populate devices

mount -t devtmpfs devtmpfs /dev

# Setup dynamic libraries

mkdir -p /usr/lib64
ln -s /usr/local/musl/lib/crt1.o /usr/lib64/crt1.o
ln -s /usr/local/musl/lib/crti.o /usr/lib64/crti.o
ln -s /usr/local/musl/lib/crtn.o /usr/lib64/crtn.o
ln -s /usr/local/musl/lib/libc.a /usr/lib64/libc.a

ln -s /usr/local/musl/include/* /usr/include/

mkdir -p /lib64
ln -s /usr/local/musl/lib/libc.so /lib/ld-musl-x86_64.so.1
ln -s /usr/local/musl/lib/libc.so /lib64/ld-linux-x86-64.so.2
ln -s /usr/local/musl/lib/libc.so /usr/lib/libc.so
ln -s /usr/local/musl/lib/libc.so /lib/libc.so

# Setup loopback for network

ifconfig lo up
echo "nameserver 8.8.8.8" > /etc/resolv.conf
route add default gw 10.0.2.2

chmod +x kaoru/oksh
ln -sf /kaoru/oksh /usr/bin/oksh
ln -sf /kaoru/oksh /bin/oksh

if [ $(id -u) -eq 0 ]; then
    export PS1='\[\033[01;31m\][\u@kaoru \w]# \[\033[00m\]'
else
    export PS1='\[\033[01;32m\][\u@kaoru \w]$ \[\033[00m\]'
fi

chown root:root bin/busybox bin/oksh
chmod 4755 bin/busybox
chmod 4755 bin/login
chmod 4755 bin/su

clear
echo "Welcome to Kaoru Linux!"
. /etc/profile
setsid cttyhack /kaoru/oksh
. /etc/profile
export PATH=$PATH:/sbin:/usr/sbin
