#!/bin/sh

# Mount /proc and /sysfs

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -o remount,rw /

# Setup loopback for network

ifconfig lo up

if [ $(id -u) -eq 0 ]; then
    export PS1='\[\033[01;31m\][\u@kaoru \w]# \[\033[00m\]'
else
    export PS1='\[\033[01;32m\][\u@kaoru \w]$ \[\033[00m\]'
fi

clear
echo "Welcome to Kaoru Linux!"

. /etc/profile
setsid cttyhack /kaoru/oksh
. /etc/profile

